import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import { SidebarProvider } from "@/components/ui/sidebar"
import  {AppSidebar}  from "@/components/AppSidebar"
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Nexus | Dashboard",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased flex items-start h-full bg-[#F8F9FC]`}
      >
        <SidebarProvider>
          <AppSidebar />
          {/* <SidebarTrigger /> */}
        </SidebarProvider>
        <main className="w-full min-h-full ml-[300px]">{children}</main>
      </body>
    </html>
  );
}
